package com.econome.app.model;

import jakarta.persistence.*;

/**
 * This is a JPA entity class for the Type table in the database.
 * It represents a type that can be assigned to a transaction.
 */
@Entity
@Table(name = "type")
public class Type {

    /**
     * The unique identifier for the type.
     * It is automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The name of the type.
     */
    @Column(name = "name")
    private String name;

    // getters and setters

    /**
     * Returns the unique identifier of the type.
     *
     * @return The unique identifier of the type.
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the unique identifier of the type.
     *
     * @param id The unique identifier of the type.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Returns the name of the type.
     *
     * @return The name of the type.
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the name of the type.
     *
     * @param name The name of the type.
     */
    public void setName(String name) {
        this.name = name;
    }
}